### ISSUE TITLE
I lose all my wallet files( incloud .key file), and i find coinhive.com  paid already

### ISSUE THREAD

**Issue by pangguoming** [cazala/coin-hive#105]
i lose all my wallet files( incloud .key file), and i find coinhive.com  paid already
what can i do to get my xmr back?

**Comment by AgentConDier** [comment]
Unless you have your passphrase/private key somewhere, your monero is gone. I don't think this is not the right place for this question.

**Comment by pangguoming** [comment]
thanks for your answer @AgentConDier
