### ISSUE TITLE
Ubuntu 16.04.4 -> Errors

### ISSUE THREAD

**Issue by Jpofin** [cazala/coin-hive#112]
when running coin-hive 0NhxZMXyTUaFFAOlPOHXeEcVX92cjwGa --username 2988567

this happens:
/usr/lib/node_modules/coin-hive/bin/coin-hive:25
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

Does anyone had the same issue and could help me with that?

It's a dedicated physical machine.

I've done the steps in troubleshooting to install it:
sudo apt-get -y install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget libxext6

sudo npm i -g coin-hive --unsafe-perm=true --allow-root

**Comment by FlareCO** [comment]
hello,

can you try
coin-hive your-token --username=jpofin

**Comment by Jpofin** [comment]
Same Issue.
It also happens when only running coin-hive without anything else.

**Comment by Jpofin** [comment]
It was my node.js being under version 8.
I installed version 10 and now it's working

`curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs`
