### ISSUE TITLE
Coin-Hive Blocked By BitDefender

### ISSUE THREAD

**Issue by indiespace** [cazala/coin-hive#15]
Using chrome browser bit defender blocks coinhive.min.js from being loaded giving 403 error.
Couldn't even use the contact form on the con-hives website because of the proof of work captcha wouldn't work because of this.

**Comment by cazala** [comment]
This project is [not related](https://github.com/cazala/coin-hive#disclaimer) to `coin-hive.com`, you should contact them for this issue.
