### ISSUE TITLE
just a question.

### ISSUE THREAD

**Issue by systemroot** [cazala/coin-hive#16]
>I've read your alert.

So what does this project do? is this just a simple page or can do more than that?
imean, i was testing coin-hive and thinking to open a pool with it. but something weired was happening while on mining page hash rate is 100+Hash/sec from just one pc my hash rate at coin-hive dashboard is just 60hash/sec :confused: (testing with coin-hive javascript way)

So is this project optimized somehow or you just created a simple page?!
Thanks.

**Comment by systemroot** [comment]
looks like a simple page from here
>https://github.com/cazala/coin-hive/blob/master/src/server.js#L6

**Comment by soyuka** [comment]
Hi, this project allows you to run `coin-hive` on a server by emulating a browser (using [puppeteer](https://github.com/GoogleChrome/puppeteer) and rendering a CoinHive miner.

Nothing different then the javascript coin-hive, just runs on a server instead of your computer's browser.

**Comment by cazala** [comment]
Oh and regarding the hash rate, if you run this package without specifying a number of threads, it will set it to the number of CPU cores, to run as many concurrent threads as possible. In coin-hive's website the miner they have on their homepage is set by default to use only 2 threads (although you can increase that from the UI).

**Comment by systemroot** [comment]
Well thank you for informations and the great work

**Comment by jsappme** [comment]
Just a few more questions :-)

What's your h/s ? 
Are you running it on the cloud or locally?

**Comment by systemroot** [comment]
i was just testing..
my pc 129Hash/sec
and 2 vps servers one 34hash/sec and anotherone 92hash/sec

So i was around 200hash sec.
At the begin it starts to show hash ok. then in dashboard i was able to see just 60-69/hash sec while mining rate in browser wasn't going low.

In this case is happening a bad think. or coin-hive mining system isn't that good. like some old mining programs are, if nothing to mine hash will go 0h/s :confused:
