### ISSUE TITLE
puppeteer does not work in centos6.6

### ISSUE THREAD

**Issue by kingvid-chan** [cazala/coin-hive#17]
Please read this before submitting:

This project has nothing to do with `coin-hive.com`

What this package does is just the following:

1. Launch a local server that serves a page where CoinHive's Javascript miner is embedded.

2. Launch puppeteer (a headless chrome) pointing to that page.

3. Expose an API that allows you to interact with that miner from node.js (starting, stopping, etc).

The purpose of this package is to allow you to run CoinHive's JavaScript miner from node.js (otherwise it only works on the browser).

If you have an issue with CoinHive's JavaScript miner, or with coin-hive.com website, you should read their FAQs and contact them here:

https://coin-hive.com/contact

Thanks for reading ^.^ if you do have an issue with this package (have a question, found a bug, feature request) then please do submit it 

<3

**Comment by cazala** [comment]
https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
