### ISSUE TITLE
What are you smoked when developed this?

### ISSUE THREAD

**Issue by DarkJoney** [cazala/coin-hive#19]
Why I have to share my CPU time with random website owner? Damn it! 
Thanks god that KIS blocks your dumb script. 
I don't like such software engineers like U.

**Comment by sid-engel** [comment]
Would you rather share some cpu, or have to see a shit ton of ads?

I think it's a fair concept.

**Comment by soyuka** [comment]
Not related to coin-hive, please guys...

**Comment by sphericalmedia** [comment]
so can i run this independently and point it a mining pool of my chosing?

**Comment by cazala** [comment]
Oh god.. people just don't read

**Comment by cazala** [comment]
oh @sphericalmedia I didn't see your question, this package will run CoinHive's miner, which mines Monero using their mining pool. The mining pool cannot be changed.

**Comment by sphericalmedia** [comment]
no problem, thanks for reply, is there any way/ script out there that would allow me to do this? the script concept is great for people looking to get to mining and is what i need for a project but i dont want to take as a middleman. just miners recieve reward and pool receves hashrate.
