### ISSUE TITLE
GLIBC chomium issue

### ISSUE THREAD

**Issue by ghost** [cazala/coin-hive#21]
I am having the following issue when launching coin-hive across all my systems:

> An error occured Failed to launch chrome!
/home/opuser/.nvm/versions/node/v8.5.0/lib/node_modules/coin-hive/node_modules/puppeteer/.local-chromium/linux-497674/chrome-linux/chro
me: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/opuser/.nvm/versions/node/v8.5.0/lib/node_module
s/coin-hive/node_modules/puppeteer/.local-chromium/linux-497674/chrome-linux/chrome)

I think it has something to do with chromium being compiled against an old version of glibc?

**Comment by Hostile** [comment]
im getting same thing https://puu.sh/xIr3H/1c569e2a55.png

**Comment by happyDemon** [comment]
You're missing dependencies, in this case GLIBC_2.14
I'm sure you'll be missing more.
https://packages.ubuntu.com/search can help you find them
