### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sputn1k** [cazala/coin-hive#22]
Ubuntu (14.04) 
node (8.6.0)
npm (5.3.0)

error - 

```
(node:9965) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!
/home/safeuser/miner/node_modules/puppeteer/.local-chromium/linux-497674/chrome-linux/chrome: error while loading shared libraries: libpangocairo-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

(node:9965) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by soyuka** [comment]
https://github.com/cazala/coin-hive/issues/9#issuecomment-330260973

**Comment by sputn1k** [comment]
@soyuka  thanks but doesn't work - 

`sudo apt-get install libgtk-3-0 libgconf-2-4 libpangocairo-1.0-0 chromium`

Package chromium is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  chromium-bsu:i386 chromium-bsu

E: Package 'chromium' has no installation candidate

**Comment by sputn1k** [comment]
@soyuka - Got it to work! thanks man 

After i - 
`sudo apt-get install chromium-browser`
` sudo apt-get install chromium-bsu`

Then - 
sudo npm install coin-hive --unsafe-perm=true --allow-root
