### ISSUE TITLE
How to set a userName?

### ISSUE THREAD

**Issue by sputn1k** [cazala/coin-hive#26]
As per CoinHives documentation ? 
`CoinHive.User(siteKey, userName [, options])`

**Comment by nodevm** [comment]
You can just `coin-hive Phbl.... --port 3003`  where `Phbl....` is your site key.

**Comment by sputn1k** [comment]
@nodevm - I don't want to set the `siteKey` I want to set `userName`?!

**Comment by sputn1k** [comment]
Ok I checked the code there is not option to set the userName as its been set `CoinHive.Anonymous` -  `miner = new CoinHive.Anonymous(siteKey);` 

Going to fork the code.

**Comment by nodevm** [comment]
@sputn1k  I couldn't find it either. Good luck with the fork.

**Comment by sputn1k** [comment]
@nodevm If you need it or anyone else (tested and working) - https://github.com/sputn1k/coin-hive

**Comment by sputn1k** [comment]
@cazala You can merge fork if you like;)

**Comment by cazala** [comment]
feel free to send a PR @sputn1k (:

**Comment by cazala** [comment]
Now possible in [v1.4.0](https://github.com/cazala/coin-hive/releases/tag/1.4.0) thanks to #30!
