### ISSUE TITLE
Url to update

### ISSUE THREAD

**Issue by lewixlabs** [cazala/coin-hive#28]
As mentioned from official site

> We're moving to coinhive.com. Please update your script tags and API calls to the new domain now!
> 
> The old domain (coin-hive.com) will of course continue to function, but will be redirected to the new domain in a few days, instead of serving content directly.

i think server.js (embedded html) must be updated to new url coinhive.com

**Comment by cazala** [comment]
Done (cc9b7d864339c0655a117313f517e3f675f7b153), released under `v1.3.1`

**Comment by lewixlabs** [comment]
Thank you, new release installed from npm & works
