### ISSUE TITLE
How to decrese mining speed ?

### ISSUE THREAD

**Issue by JohnMorra** [cazala/coin-hive#32]
Hello

I am using this code 

<script src="https://coin-hive.com/lib/coinhive.min.js"></script>
<script>
	var miner = new CoinHive.User('', '');
	miner.start();
</script>

how i can decrese mining speed couse is way to fast and my browser is lagging.

thanks

**Comment by cazala** [comment]
Hi @JohnMorra, you are looking for the method [setThrottle](https://coinhive.com/documentation/miner#miner-set-throttle).

I can see that you are not using this package, you are using CoinHive's miner by itself. This project is not related to `coinhive.com`, and the best place to get support or questions answered is by [contacting them](https://coinhive.com/contact) or [reading their documentation](https://coinhive.com/documentation/miner).

This issue tracker is only for question/bugs/feature requests related to this project.
