### ISSUE TITLE
Error: Cannot find module 'coin-hive'

### ISSUE THREAD

**Issue by alfredovilla** [cazala/coin-hive#35]
Hi! On the my apple mac with node.js and npm (last release) after installing "npm install -g coin-hive" and execute your demo .js , i have this errore: Cannot find module 'coin-hive'...

Why?

**Comment by sunk818** [comment]
did you look for coin-hive executable? how about `./coin-hive` 

mine installed in ubuntu 17 and it was in ~/node_modules/coin-hive/bin

unless you're doing this just for fun, you're better off running compiled programs like `[xmr-stak-cpu](https://github.com/fireice-uk/xmr-stak-cpu)` (and amd/nvidia versions) that will give you a higher hash rate.

**Comment by cazala** [comment]
It looks like it wasn't installed. You can try to install it locally in the directory where you have that .js file: `npm init && npm i --save coin-hive`
