### ISSUE TITLE
Can I run multiple instances ?

### ISSUE THREAD

**Issue by isbkch** [cazala/coin-hive#36]
Is there a way to run multiple instances (on multiple browser) each one with its own wallet address ?

**Comment by sunk818** [comment]
did you mean to [contact coinhive.com](https://coinhive.com/contact) - cazal's code runs on the server via node.js

on coinhive.com, you can only have one wallet address per account. there's nothing stopping you from creating multiple accounts, each with their own payment address. you do understand though how many hashes you need just to get a payout of 0.5 XMR? each account would need 3.546 billion hashes. If you could compute 100 H/s all day long, it would take you 410 days. 3546/(100*60*60*24/1000000). why would you want to run multiple instances when even one payout is so hard to do?

**Comment by cazala** [comment]
You can run multiple instances of this package if that's what you are asking, you just need to launch each in different ports.

**Comment by sunk818** [comment]
How do you run them in different ports?

**Comment by cazala** [comment]
If you are using the miner programatically, you can pass a `port: XXXX` property in the constructor options.

If you are using the CLI you can pass a `--port=XXXX` argument .
