### ISSUE TITLE
ubuntu 16.04 errors

### ISSUE THREAD

**Issue by Hostile** [cazala/coin-hive#38]
Initializing...
An error occured Failed to launch chrome!
/usr/lib/node_modules/coin-hive/node_modules/puppeteer/.local-chromium/linux-497674/chrome-linux/chrome: error while loading shared libraries: libpangocairo-1.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

**Comment by cazala** [comment]
try:

```
sudo apt-get install libgtk-3-0 libgconf-2-4 libpangocairo-1.0-0 chromium
```

**Comment by Hostile** [comment]
ok got it working, heres dependiencies for it to work

You might want to add this in your readme.

 sudo apt-get -y install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

**Comment by cazala** [comment]
thanks!
