### ISSUE TITLE
Let client perform the hashing but on custom pool?

### ISSUE THREAD

**Issue by sunk818** [cazala/coin-hive#41]
Hi, thanks for this. So far, I've gotten this to work on a Ubuntu 16/17 server pointing to a custom pool. Been having issues seeing up the coin hive proxy. 

Is there a way to use this code so a web page you run on a browser points to a custom pool?

**Comment by sunk818** [comment]
Maybe this is the answer? https://minero.pw/#/

**Comment by cazala** [comment]
You can, you will need to setup a proxy and then configure the CoinHive miner to point to your proxy.
