### ISSUE TITLE
Initializing... An error occured wss is not defined (Ubuntu 17)

### ISSUE THREAD

**Issue by sunk818** [cazala/coin-hive#42]
Coin-Hive has been running fine since yesterday. Today, I tried install today on Ubuntu 17 instead of 16 LTS. For some reason on new installations, I am getting the following error.

> Initializing...
> An error occured wss is not defined

Works fine if I just do `sudo ./coin-hive coin_hive_public_key`

But if I try to do custom stratum pool (e.g. --username, --pool-host, --pool-port), I get this error.

**Comment by cazala** [comment]
Fixed in version `1.6.3`
