### ISSUE TITLE
Using custom pool, has anyone been able to get "Accepted" to go up from 0 to 1?

### ISSUE THREAD

**Issue by sunk818** [cazala/coin-hive#45]
Just curious... I'm connecting to a custom pool but not seeing the "Accepted" count go up from 0 to 1. Is anyone else getting the count to go up? I'm pretty sure some hashes are being accepted though...

**Comment by majkelo** [comment]
nor do I - I tried default config and after ~15k hashes I haven't got any accepted hash.

**Comment by cazala** [comment]
Yep.. it was broken 😅 @forever1306 fixed it in #44 and I just released it under `v1.6.5`.. I just tested it on mineXMR.com and it's working:

<img width="786" alt="screen shot 2017-10-15 at 3 40 59 pm" src="https://user-images.githubusercontent.com/2781777/31587890-f48baf1e-b1e9-11e7-85ed-316cb9e0e950.png">
