### ISSUE TITLE
Is 1.6.5 working correctly? An error occured Unhandled "error" event. ([object Object])

### ISSUE THREAD

**Issue by sunk818** [cazala/coin-hive#47]
I had to install 1.6.3 for coin-hive to run properly on a custom pool. When I tried to run 1.6.5 with a custom pool, I get the following error.

`An error occured Unhandled "error" event. ([object Object])`

**Comment by cazala** [comment]
It was working fine for me on pool.minexmr.com:4444, which pool are you mining on?

**Comment by sunk818** [comment]
Powered by  cryptonote-universal-pool v1.1.5_uni open sourced under the GPL -- seems like the same pool everyone else is using for cryptonight coins.

**Comment by sunk818** [comment]
I'll try from a different server and see if it makes a difference.

**Comment by cazala** [comment]
Try with `v1.7.0`, it has fixes and improvement coming from a new version of `coin-hive-stratum`
