### ISSUE TITLE
Question/Request: Pool password functionality

### ISSUE THREAD

**Issue by hilutd** [cazala/coin-hive#48]
Some pools are require password, either for authentication or tracking.

Is it possible to add a password in the pool configuration? If not, is it possible to add it in the future?

**Comment by hilutd** [comment]
Basically, we are talking about making this line below, configurable:

https://github.com/cazala/coin-hive-stratum/blob/61a0356d09b64b4e6410c4f04b03a6eab39f5372/src/proxy.js#L79

**Comment by cazala** [comment]
Yep, that's on my todo list..

**Comment by cazala** [comment]
Done (3be28d1f34cc4be18b812c98e21edb1de9d46919) this is available under release `1.7.0`
