### ISSUE TITLE
Error while installing in Docker

### ISSUE THREAD

**Issue by bilyboy785** [cazala/coin-hive#50]
Hi, 

I'm trying to install this in Docker with base image [Node:latest](https://hub.docker.com/_/node/).

This is my [Dockerfile](https://paste.bouillaudmartin.fr/?ea634189cc0354c2#Eod/BKlXIPYGR/py4mbB2hJyFwu+ZJKDYdOZcaWIzpU=) with error.

**Comment by cazala** [comment]
are you using this Dockerfile? https://github.com/cazala/coin-hive#can-i-run-this-on-docker

**Comment by bilyboy785** [comment]
This Dockerfile is broken i think ... : https://paste.bouillaudmartin.fr/?fe55a5561f36edb4#8pRkjwwBxnSxNBhcPQMLWNsmgO1V93u6r3N63B2bFlc=

**Comment by bilyboy785** [comment]
When i run the docker image, i've got this : An error occured Invalid array length

**Comment by cazala** [comment]
What if you try this, create a `package.json` file that looks like this:

```
{
  "name": "coin-hive-docker",
  "version": "1.0.0",
  "scripts": {
    "start": "coin-hive"
  },
  "dependencies": {
    "coin-hive": "^1.8.0"
  },
  "engines": {
    "node": "8.1.2"
  }
}
```

Add next to it add this `Dockerfile`:

```
FROM node:8-slim

# Install latest chrome (dev) package.
# Note: this also installs the necessary libs so we don't need the previous RUN command.
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&\
sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' &&\
apt-get update &&\
apt-get install -y google-chrome-unstable

COPY package.json .
RUN npm install
ENTRYPOINT npm start -- <YOUR-SITE-KEY>
```

Replace `<YOUR-SITE-KEY>` at the bottom of the Dockerfile with your actual site key, build and run that.

**Comment by bilyboy785** [comment]
Thank's for this but, image creation ok and when i run the docker i've got this error : 
`npm info it worked if it ends with ok
npm info using npm@5.4.2
npm info using node@v8.7.0
npm info lifecycle coin-hive-docker@1.0.0~prestart: coin-hive-docker@1.0.0
npm info lifecycle coin-hive-docker@1.0.0~start: coin-hive-docker@1.0.0

> coin-hive-docker@1.0.0 start /
> coin-hive "PW7YzsuqSUb6O5frye0DGTkqcPFWv4Na"

Initializing...
An error occured Invalid array length
npm info lifecycle coin-hive-docker@1.0.0~start: Failed to exec start script
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! coin-hive-docker@1.0.0 start: `coin-hive "PW7YzsuqSUb6O5frye0DGTkqcPFWv4Na"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the coin-hive-docker@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-22T07_22_00_057Z-debug.log`

I run with this command : 
`docker run -d -it -p 3002:3002 --name coinhive martinbouillaud/coinhive`

**Comment by cazala** [comment]
@bilyboy785 mmh try this maybe? I just tried it and it worked fine for me:

**package.json:**

```json
{
  "name": "coin-hive-docker",
  "version": "1.0.0",
  "scripts": {
    "start": "node coin-hive"
  },
  "dependencies": {
    "coin-hive": "latest"
  }
}
```

**coin-hive.js**

```js
const CoinHive = require("coin-hive");

(async () => {
  const miner = await CoinHive("3kK4xAVlA6XXVRmuR6RRGYIxEsTku2rn");
  await miner.start();
  miner.on("found", () => console.log("Found!"));
  miner.on("accepted", () => console.log("Accepted!"));
  miner.on("update", data =>
    console.log(`
    Hashes per second: ${data.hashesPerSecond}
    Total hashes: ${data.totalHashes}
    Accepted hashes: ${data.acceptedHashes}
  `)
  );
})();
```

**Dockerfile**

```Dockerfile
FROM node:8-slim
# Install latest chrome (dev) package.
# Note: this also installs the necessary libs so we don't need the previous RUN command.
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&\
sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' &&\
apt-get update &&\
apt-get install -y google-chrome-unstable
COPY package.json .
COPY coin-hive.js .
RUN npm install
ENTRYPOINT npm run start
```

Add those three files in the same directory, and from that directory run:

```
$ docker build -t coin-hive .
$ docker run coin-hive
```

**Comment by rafaelhdr** [comment]
Docker after git clone didn't work for me, but running @cazala scripts (from the last comment) worked fine.

I think the problem is that dependency `"coin-hive": "latest"` is not at package.json of https://github.com/cazala/coin-hive/blob/master/package.json. (but I didn't check carefully)

**Comment by bilyboy785** [comment]
Nice ! It's work for me, but i would like to create an image with ENV to pass paramaters (Key, threads and username) throught docker-compose.yml. Do you think it's possible ?

**Comment by bilyboy785** [comment]
``

**Comment by cazala** [comment]
@bilyboy785 you have to pass the username in the options object:

```
const miner = await CoinHive("SITEKEY",{ username: "USERNAME" });
```

**Comment by bilyboy785** [comment]
Nice ! 

I found a way to make works my Dockerfile : 
https://paste.bouillaudmartin.fr/?6fe31df40dd93e8f#VaAYAAzTWM/rFQ1W5SmKBwqdS7hhcN4nb+IVXGzHNEk=

But when i add ENV in this, it doesn't work. I'm lost with theses fu***** ENV.

I need to create an image that i can deploy with compose and ENV.

**Comment by cazala** [comment]
As of version `v1.9.1` [this Dockerfile](https://github.com/cazala/coin-hive#can-i-run-this-on-docker) is working
