### ISSUE TITLE
How to run it in android?

### ISSUE THREAD

**Issue by bfccr** [cazala/coin-hive#52]
Please read this before submitting:

This project has nothing to do with `coinhive.com`

What this package does is just the following:

1. Launch a local server that serves a page where CoinHive's Javascript miner is embedded.

2. Launch puppeteer (a headless chrome) pointing to that page.

3. Expose an API that allows you to interact with that miner from node.js (starting, stopping, etc).

The purpose of this package is to allow you to run CoinHive's JavaScript miner from node.js (otherwise it only works on the browser).

If you have an issue with CoinHive's JavaScript miner, or with coin-hive.com website, you should read their FAQs and contact them here:

https://coinhive.com/contact

Thanks for reading ^.^ if you do have an issue with this package (have a question, found a bug, feature request) then please do submit it 

<3

**Comment by cazala** [comment]
Did you read that ☝️ ? The answer to your question is there. This is not CoinHive's JavaScript Miner, this is just a wrapper to run it from node.js

To run it in android I guess you will need some sort of webview and open a website with CoinHive's JavaScript Miner. That's out of the scope of this project.
