### ISSUE TITLE
Using pool in options object

### ISSUE THREAD

**Issue by adack123** [cazala/coin-hive#53]
Hey there, 

I have a question regarding the pool option. I'm catching this promise rejection 
`{ error: 'invalid_site_key' }` whenever I put in a `pool` with the subsequent properties. I know that the site key I'm using is valid because if I remove the `options` object in general it works. 

My question is, is this a cryptic error that is potentially something else? I've been using the default pool provided in the example.

**Comment by cazala** [comment]
When you use a custom pool you don't use a site key, you use a monero address. You are getting that error because you are not providing a monero address.

**Comment by adack123** [comment]
Awe makes sense, I knew it was a noob mistake! Thanks.

**Comment by cazala** [comment]
np (;
