### ISSUE TITLE
Embed miner into webpage

### ISSUE THREAD

**Issue by JPaulMora** [cazala/coin-hive#55]
Hey! awesome work! How can I embed this into my webpage? I tried editing the miner.js without luck. Am I missing the ready-made js?

**Comment by cazala** [comment]
You can use [CoinHive Proxy] to get you own proxy and a snippet you can embed on your website to use the miner.

**Comment by JPaulMora** [comment]
Cool, can you specify your own pool? I see you only included the biggest ones

**Comment by cazala** [comment]
I just added the ability to do it. Select the last option `Custom Pool` and enter `Host`, `Port` and `Difficulty`.

**Comment by JPaulMora** [comment]
Beautiful! Using now :)
