### ISSUE TITLE
Run Coin-Hive without puppeteer

### ISSUE THREAD

**Issue by devswon** [cazala/coin-hive#56]
Any idea how to run the coin-hive package with nodejs without using Puppeteer or ideas for developing monero miner for nodejs. Thanks

**Comment by soyuka** [comment]
Why? If you want a real miner just take [xmrig](https://github.com/xmrig/xmrig). Javascript isn't the best language when it comes to high-cpu tasks IMO.

**Comment by devswon** [comment]
@soyuka Ok, thanks for your response, appreciate it.
