### ISSUE TITLE
Failed at the puppeteer@0.10.2 install script.

### ISSUE THREAD

**Issue by JuanMao1997** [cazala/coin-hive#58]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@0.10.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@0.10.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-29T10_08_26_337Z-debug.log

root@123:~# npm -v
5.4.2
root@123:~# node -v
v8.8.1

**Comment by SoftCreatR** [comment]
Try with

`sudo npm i -g coin-hive --unsafe-perm=true --allow-root`

**Comment by soyuka** [comment]
don't install as root ?

**Comment by emanuelecesari** [comment]
I am having the same problem..
I tryed 2 times in you different system ubuntu and arch linux..
How I could install it?

my node version is v8.6.0
my npm version is 5.5.1

**Comment by emanuelecesari** [comment]
I have the same problem..
node version v8.6.0
npm version 5.5.1

**Comment by GigaFyde** [comment]
use
`curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -`

then use
`sudo apt-get install -y nodejs`

Then try to re-install again.
It worked for me.

**Comment by SoftCreatR** [comment]
But it requires Node8 and not Node6?

**Comment by Katamori** [comment]
`sudo npm i -g coin-hive --unsafe-perm=true --allow-root` and installing Node 6.4.0.+ solved for me.
