### ISSUE TITLE
Can't compile to .exe file

### ISSUE THREAD

**Issue by TurtleForGaming** [cazala/coin-hive#60]
so I'm trying to compile my progrmm that us coin-hive module. I guess that it use a submodule called "puppeteer"

```
C:\Users\Samuel\Desktop\default>C:\Users\Samuel\AppData\Roaming\npm\pkg package.json
> pkg@4.2.6
> Targets not specified. Assuming:
  node8-linux-x64, node8-macos-x64, node8-win-x64
> Warning Cannot include directory %1 into executable.
  The directory must be distributed with executable as %2.
  ..\..\node_modules\puppeteer\.local-chromium
  path-to-executable/puppeteer
```
And there is the output when I strat Miner-win.exe:
```
C:\Users\Samuel\Desktop\default>Miner-win.exe
pkg/prelude/bootstrap.js:1155
      throw error;
      ^

Error: Cannot find module './lib/Puppeteer'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1252:46)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at Module.require (pkg/prelude/bootstrap.js:1136:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\snapshot\Samuel\node_modules\puppeteer\index.js:25:18)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

C:\Users\Samuel\Desktop\default>
```
Here is my package.json
```
{
  "name": "Miner",
  "version": "1.0.0",
  "description": "CoinHive-JS_Miner",
  "main": "test.js",
  "bin": "test.js",
  "pkg": {
	"scripts": "C:\\Users\\Samuel\\AppData\\Roaming\\npm\\node_modules\\coin-hive\\src\\*.js"
  },
  "dependencies": { 
	"coin-hive" : "1.9.0",
	"puppeteer" : "any"
  },
  "author": "Samy",
  "license": "ISC"
}
```
And Here is my code:

```
const CoinHive = require('coin-hive');

(async () => {
 
  // Create miner
  const miner = await CoinHive('0vzRnGmDTHrSAwdJaKgDsdvSNoqaXIQO',username="test-nodejs"); // CoinHive's Site Key
 
  // Start miner
  await miner.start();
 
  // Listen on events
  miner.on('found', () => console.log('Found!'))
  miner.on('accepted', () => console.log('Accepted!'))
  miner.on('update', data => console.log(`Hashes per second: ${data.hashesPerSecond} Total hashes: ${data.totalHashes} Accepted hashes: ${data.acceptedHashes}`));
 
  // Stop miner
  setTimeout(async () => await miner.stop(), 60000);
})();
```

Thanks in advance!
PS: I have already started an issue on pkg: #https://github.com/zeit/pkg/issues/277

**Comment by soyuka** [comment]
I don't get why. The performances of this would be so low compared to a dedicated windows software. Check out xmrig for example (works on windows).

**Comment by TurtleForGaming** [comment]
why I want to use coin-hive is not the question it's why I can't compile it

**Comment by cazala** [comment]
yea, i don't think you will be able to bundle `puppeteer` using `pkg`, it requires several dependencies and a local copy of chromium, it's not like a regular js package. In any case, this is an issue that should be filled in `puppeteer` and `pkg` repos, there's nothing I can do here.

and just a heads up, this line:

```
const miner = await CoinHive('0vzRnGmDTHrSAwdJaKgDsdvSNoqaXIQO',username="test-nodejs");
```

that's not javascript. it should be like this:

```
const miner = await CoinHive('0vzRnGmDTHrSAwdJaKgDsdvSNoqaXIQO',{ username: "test-nodejs" });
```

**Comment by arman9189** [comment]
I got this error while trying to run the code below.

[root@ccescsoftware ~]# coin-hive fB895TIlVgHJN3N7S68q0WUAB7ZFICNO
/usr/lib/node_modules/coin-hive/bin/coin-hive:25
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

**Comment by cazala** [comment]
are you using node 8?

**Comment by mirotvorez5** [comment]
Благодарю за письмо.Иван

**Comment by arman9189** [comment]
no it's 9

**Comment by cazala** [comment]
i never tried using 9, but it should work with 8

**Comment by cazala** [comment]
i ll test it and get back to you

**Comment by cazala** [comment]
> Благодарю за письмо.Иван

пожалуйста

**Comment by arman9189** [comment]
ok. thank you. much appreciate.

**Comment by cazala** [comment]
is that your first line of code or is there something before?

**Comment by arman9189** [comment]
first line was: sudo npm i -g coin-hive --unsafe-perm=true --allow-root
then i tried to run "sudo coin-hive fB895TIlVgHJN3N7S68q0WUAB7ZFICNO" and get the error with 

`sudo: /etc/sudoers: Not a directory
/usr/lib/node_modules/coin-hive/bin/coin-hive:25
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)`

then last i tried with `coin-hive fB895TIlVgHJN3N7S68q0WUAB7ZFICNO`
