### ISSUE TITLE
OSX stop running after 20 sec

### ISSUE THREAD

**Issue by EasonWang01** [cazala/coin-hive#62]
Please read this before submitting:

This project has nothing to do with `coinhive.com`

What this package does is just the following:

1. Launch a local server that serves a page where CoinHive's Javascript miner is embedded.
```js
const CoinHive = require('coin-hive');

(async () => {

  // Create miner
  const miner = await CoinHive('site key'); // CoinHive's Site Key

  // Start miner
  await miner.start();

  // Listen on events
  miner.on('found', () => console.log('Found!'))
  miner.on('accepted', () => console.log('Accepted!'))
  miner.on('update', data => console.log(`
    Hashes per second: ${data.hashesPerSecond}
    Total hashes: ${data.totalHashes}
    Accepted hashes: ${data.acceptedHashes}
  `));

  // Stop miner
  setTimeout(async () => await miner.stop(), 60000);
})();
```
The first 20 sec success mining but then it paused.
<img width="467" alt="2017-11-10 8 40 47" src="https://user-images.githubusercontent.com/11001914/32637146-276bf3b8-c5f3-11e7-8f9b-dfdce09f9dca.png">

2. Launch puppeteer (a headless chrome) pointing to that page.

3. Expose an API that allows you to interact with that miner from node.js (starting, stopping, etc).

The purpose of this package is to allow you to run CoinHive's JavaScript miner from node.js (otherwise it only works on the browser).

If you have an issue with CoinHive's JavaScript miner, or with coinhive.com website, you should read their FAQs and contact them here:

https://coinhive.com/contact

Thanks for reading ^.^ if you do have an issue with this package (have a question, found a bug, feature request) then please do submit it 

<3

**Comment by cazala** [comment]
if that's the code you are using, the last line says:

```js
// Stop miner
setTimeout(async () => await miner.stop(), 60000);
```

Just remove it if you don't want the miner to stop. The purpose of that code was to show some methods and events the miner has.
