### ISSUE TITLE
extract a coinhive.js core instead

### ISSUE THREAD

**Issue by BransonGitomeh** [cazala/coin-hive#64]
hey after reading through the codebase that coin-hive provides, it makes a lot of reference to window and other browser features, wouldn't it be more feasible if someone managed to extract the mining code and the the code that connects to the servers and package it in a way that it can be used in another environment ie react-native or embed in ones own code to avoid blockers that are url based. how hard would it be to extract this parts and get them working without a window environment, which would also mean we may not need to use headless chrome

**Comment by cazala** [comment]
Yes, that could work. I've tried it with a bunch of other people without success tho. We tried to polyfill all the required dependencies without luck (xhr, webworkers, etc)... we didn't invest that much time on it tho, i'm not saying it's not possible.. just not that straight forward.

**Comment by BransonGitomeh** [comment]
I tried using jsDOM to poly-fill the window and fell flat on a part of the code where they make a `new Blob()` which is not available in node, i replaced that with buffer but after execution it just ddnt make a connection. Just wanted to see if you guys made any progress. what issues did you run into?

**Comment by cryptonoter** [comment]
I think this might be what is needed. I have done up a open source js web miner into your own server: https://github.com/cryptonoter/CryptoNoter

**Comment by cazala** [comment]
isn't that justa copy of [deepMiner](https://github.com/deepwn/deepMiner) ? which uses CoinHive's miner under the hood... they did not extract the core so it can be run out of the browser, it's still a web miner... so I don't see how does it relate to the topic of this issue...

**Comment by cryptonoter** [comment]
I think i misunderstood the question. basically coinhive is the base code
behind cryptoloot, deepminer, cryptonoter, minerrocks. Too many to count.
