### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by FectLysh** [cazala/coin-hive#67]
Hey!

When i try "npm install -g coin-hive" it says can't find module '[PATH]/install'. And in your files there isn't a "install" file.  Maybe i am just to stupid.

Please help.

**Comment by cazala** [comment]
which versions of `node` and `npm` are you using?

```
node -v
npm -v
```

also, have you tried:

```
sudo npm i -g coin-hive --unsafe-perm=true --allow-root
```

?

**Comment by Lakloth** [comment]
Also updating your Node version could help. For me it did.
