### ISSUE TITLE
It is possible to use another Cryptocurrency, rather than XMR  Monero ?

### ISSUE THREAD

**Issue by umair-khanzada** [cazala/coin-hive#68]
It would be great if you add other Cryptocurrencies feature like **Bitcoin, Ethereum** or any other.

**Comment by sunk818** [comment]
No. Different algorithm. There's no JavaScript miner for them.

**Comment by cazala** [comment]
Actually, you can use any currency based on [CryptoNight](https://en.bitcoin.it/wiki/CryptoNight). 

So far users have been successful mining [Monero (XMR)](https://getmonero.org/) and [Electroneun (ETN)](http://electroneum.com/).

You can mine XMR on `pool.supportxmr.com`:

```
coin-hive <XMR-ADDRESS> --pool-host=pool.supportxmr.com --pool-port=3333
```

You can mine ETN on `uspool.electroneum.com`:

```
coin-hive <ETN-ADDRESS> --pool-host=uspool.electroneum.com --pool-port=3333
```

**Comment by cazala** [comment]
I added an example to the readme: https://github.com/cazala/coin-hive#can-i-mine-other-cryptocurrency-than-monero-xmr
