### ISSUE TITLE
Refactor options

### ISSUE THREAD

**Issue by soyuka** [cazala/coin-hive#7]
Hi,

Good thing I searched github before doing this haha. Works great, may I refactor options parameters with objects instead of arguments (especially in `puppeteer`)?

Also, I would like to add `minimist` so that you could give actual arguments name to the binary (ie `coin-hive --threads X --host Y`).

About the update, do you know some CLI package that would allow something a bit prettier? There's a good list [here](https://github.com/sindresorhus/awesome-nodejs#command-line-utilities), in pm2 we're using [multimeter](https://www.npmjs.com/package/pm2-multimeter).
 
WDYT?

**Comment by cazala** [comment]
Sounds good (: I see you did a PR, I ll take a look at it later after work 👍

**Comment by soyuka** [comment]
I'll do a cleaner one soon ;).
