### ISSUE TITLE
how to connect to the pool

### ISSUE THREAD

**Issue by avnerbarr** [cazala/coin-hive#70]
I've followed the instructions here: https://github.com/cazala/coin-hive-stratum/wiki/Deploy-to-now.sh-and-GitHub-Pages

I've forked the assets repo, and I've created a now.sh instance.

But I don't understand what is supposed to happen in this part of the instructions:

<script src="https://avnerbarr.github.io/yonitost-proxy/m.js?proxy=wss://yonitost-proxy.now.sh?pool=HOST:PORT"></script> <<<< Which pool should I be using?
<script>
  var miner = CH.Anonymous('SITE_KEY'); <<< What is the SITE_KEY?
  miner.start();
</script>

Thanks!

**Comment by cazala** [comment]
That guide is to deploy a `coin-hive-stratum` proxy, this is a different repo.

**Comment by avnerbarr** [comment]
I'll move it, thanks,
