### ISSUE TITLE
optimizing for very short sessions

### ISSUE THREAD

**Issue by avnerbarr** [cazala/coin-hive#71]
Is there a guideline for dealing with very short sessions ,  perhaps 1-2 seconds. How does the difficulty impact the effectiveness? Is there something we can do to deal with the short sessions that might happen?

**Comment by cazala** [comment]
1-2 seconds is too short to achieve anything. So far the best results I've seen for short sessions is mining Electroneum instead of Monero, since pools have a very low difficulty. Check this issue for examples on how to mine ETN: #68

**Comment by sunk818** [comment]
Even coinhive with 256 difficulty and accepting all hash means the client has to have 128 H/s to submit a group of 256 hashes.

> Electroneum

I think there's an opportunity here for a pool to create a cryptonote multipool. I don't know why no one has done it. Besides XMR, there's so many other coins that has potential and low difficulty. I'm having such a difficulty time trying to get to 0.5 XMR on 500 H/s, but other coins you can mine, hodl other Cryptonight coins, and hope value rises.

**Comment by cazala** [comment]
Here's an example on how to connect to MineKitten.io ETN Pool: https://github.com/cazala/coin-hive#can-i-mine-other-cryptocurrency-than-monero-xmr

It has a difficulty of `100`, that's the lowest I've found so far.
