### ISSUE TITLE
Hidden dev fee?

### ISSUE THREAD

**Issue by magicsunday** [cazala/coin-hive#73]
You should point out that you included a hidden dev fee in this package!

**Comment by magicsunday** [comment]
Like here: https://github.com/nidscom/coin-hive

**Comment by supersurfer92** [comment]
Discussed here https://github.com/cazala/coin-hive/issues/43

**Comment by cazala** [comment]
The dev fee is mentioned two times in the readme and is configurable via the CLI and the API.

**Comment by cazala** [comment]
Sorry, three times (also via Environment Variables)

**Comment by gauntface** [comment]
I might be good to call it out clearly at the top of the README or at least give it a section dedicated to "Support This Project via Dev Fee" and explain the use.

**Comment by cazala** [comment]
I added another mention of it at the `Support` section. Usage it's explained on the respective sections (CLI, API, or ENV VARS).
