### ISSUE TITLE
How to use your package to mine Electroneum

### ISSUE THREAD

**Issue by ZeroGravityLG** [cazala/coin-hive#78]
Hello there,

I have a website with over 20.000 visitors per day and so far i am using coin hive to mine but i am very dissapointed.

Is there any possibility to use your package to mine Electroneum?
I have a dedicated server that already has node.js enable.

How can i contact you Juan?

Thanks

**Comment by SpencerWoo** [comment]
https://github.com/cazala/coin-hive#can-i-mine-other-cryptocurrency-than-monero-xmr

**Comment by ZeroGravityLG** [comment]
I have already seen this... but i can't find the way to load your files to my website or which files i need to include on my website to use coinhive to mine Electroneum? Can i have some details please or can you please let me know how can i contact you for paid services?

**Comment by cazala** [comment]
https://github.com/cazala/coin-hive/issues/77#issuecomment-353071648
