### ISSUE TITLE
Why puppeteer?

### ISSUE THREAD

**Issue by philkunz** [cazala/coin-hive#79]
I wonder: Why do you use puppeteer? nodejs already provides the v8 engine, doesn't it?

**Comment by soyuka** [comment]
because the original script runs in the browser, not sure you can run wasm scripts in node?

**Comment by evil7** [comment]
bcs some JavaScript functions in coinhive's codes only working for the browser. like some function to get CPU cores number and `Worker`. If you wanna running wasm in node in your OS. Why `nodejs` in used. `C / C++` more fast than it. Why not to running a `ccminer` or ELF miner to mining more?

**Comment by soyuka** [comment]
@evil7 Exactly what I'm saying to everyone, this has a really low interest and real miner like xmrig are way better on an actual server.

**Comment by philkunz** [comment]
makes sense.
