### ISSUE TITLE
Wordpress code

### ISSUE THREAD

**Issue by johnkeyler** [cazala/coin-hive#8]
Hello guys;

Can you share html code for wordpress? I want to use coin-hive on my wordpress.

Thank you!

**Comment by mindbreaker** [comment]
https://coin-hive.com/documentation/miner

**Comment by soyuka** [comment]
disclaimer isn't big enough ^^ This project is not directly related to coin-hive...

**Comment by cazala** [comment]
You don't need this package to run Coin-Hive on you website, you can use their [JavaScript Miner](https://coin-hive.com/documentation/miner) as is. This is to run their miner on `node.js`.
