### ISSUE TITLE
Options setting not work

### ISSUE THREAD

**Issue by davidpccu** [cazala/coin-hive#85]
Hi, thanks for the project first.

I want to set Coin-hive options (EX: threads、throttle)

And I tried with coinhive documentation example ,but it looks not working to set options in  Coin-hive

```
var miner = await CoinHive('my siteKey', {
        threads: 2,
        throttle: 0.8
    });
```
Can you give me some opinion? Thanks!

**Comment by cazala** [comment]
that should work.. what do you mean is not working?

**Comment by davidpccu** [comment]
my cpu has 8 cores
then i set threads 2 to run Coin-hive
but it looks 8 cores always run 100% to mining

i7-4790  
node -v 8.9.3

Thanks for your answer!

**Comment by coryrylan** [comment]
Ran into the same issue on macOS and Linux setups. Looks like any option via JS or CLI flags are ignored. Example passing a throttle of 0.5 still causes all threads to run at 100% usage.

**Comment by tbrenci** [comment]
It's interesting because if you look at the hashes, throttle is working, but yet it still uses 100%.

**Comment by GitHamo** [comment]
Same here.

**Comment by kennethpdev** [comment]
I actually have the same issue. Any updates?

**Comment by mirotvorez5** [comment]
Благодарю за письмо.Иван

**Comment by c0d3rw01f** [comment]
if you try to write the js code inside the same html and you tell me

On Wed, May 23, 2018 at 1:37 PM, Kenneth Palaganas <notifications@github.com

**Comment by marcelaodev** [comment]
looks like cpu continues on 100% load because it spin up a server and a puppeter

**Comment by mirotvorez5** [comment]
Благодарю за письмо.Иван
