### ISSUE TITLE
Use setup

### ISSUE THREAD

**Issue by Guilty-King** [cazala/coin-hive#9]
Can you provide directions to deploy this npm on my ubuntu 16.04 or 17.04 server , instructions needed to change the monero pool address if possible

**Comment by soyuka** [comment]
Just `node bin/coin-hive PUBLIC_KEY_HERE`.

Note that after the `npm install` you may need some dependencies : 

```
sudo apt-get install libgtk-3-0 libgconf-2-4 libpangocairo-1.0-0 chromium
```

worked for me.

You can also edit the `config/defaults` file or use an environment variable `SITE_KEY=my_key node bin/coin-hive`.

**Comment by Guilty-King** [comment]
@soyuka thnx for your help and I have looked through your help (git commit) for the project 
To explain my question technically 
As per my understanding public_key is the one you get after signing up at coin-hive.com but instead
I want to redirect all the hashing power to another destination rather than coin-hive.com 
E.g. I have a node setup at 1.2.3.4:5680 and I want to send all my hashing power to it 

Thank you for assisting me ; will this be possible?

**Comment by cazala** [comment]
Exactly (:

**Comment by cazala** [comment]
Hi @Guilty-King, now it's possible to [use a different mining pool](https://github.com/cazala/coin-hive#faq) as long as it is a stratum based one:
